### ISSUE TITLE
Multilanguage GUI

### ISSUE THREAD

**Issue by bovirus** [0-don/clippy#10]
@0-don 

Thanks for the program.

Could you please consider to enable multilanguage GUI?

Thanks.

**Comment by 0-don** [comment]
yeah, I can make that

**Comment by 0-don** [comment]
https://github.com/0-don/clippy/releases/tag/v1.3.0 added in

**Comment by bovirus** [comment]
@0-don 

Thanks.

**Comment by bovirus** [comment]
@o-don

Can I helòp you to make exe installer multilanguage?
Where can I find strings used in the instalelr?
Thanks.-
