### ISSUE TITLE
1.3.0 multilanguage - Question about it

### ISSUE THREAD

**Issue by bovirus** [0-don/clippy#13]
@0-don 

Thanks for new multimaguage UI.,

How can help toi translate also strings used in exe instalelr?
where are locate the strings for instaler in github source?

When when I run clippy 1.3.0 after installation it start in English and didn't detect Windows system language and select automatic relative language (ex. Windows in Italian - Clippy in Italian).

The Clippy UI language file are external about clippy application?
How can test a new translation in place?

**Comment by 0-don** [comment]
you need to setup the project locally to test it otherwise it wont work, the translations are in the project `src/lib/i18n`

**Comment by 0-don** [comment]
I merged your pull request `1.3.1` will be the fixed version

**Comment by bovirus** [comment]
@0-don 
What's about multilanguage installer?
Currently installer seems mono language (English).
It seems based on NSIS script.
I can help to localize it.

**Comment by 0-don** [comment]
https://v1.tauri.app/v1/guides/building/windows/#internationalization

**Comment by 0-don** [comment]
I added the langues, and hope that it works @bovirus

**Comment by bovirus** [comment]
@0-don 

Thanks.
I will test new build with multilanguage installer when it will be available.

**Comment by 0-don** [comment]
@bovirus  https://github.com/0-don/clippy/releases/tag/v1.3.1 try .exe out

**Comment by bovirus** [comment]
@0-don 

Thanks good step up.

Some issuese in the installer
Exe file porperties
Missing instalelr (decsription should be "clippy instalelr")
Missing copyright messagge like "(c) 2024 bt 0-don"

![image](https://github.com/user-attachments/assets/e8ea148c-65cf-4d8b-9cca-5a0cac5657cb)

Missing info about version that you are installing (1.3.1)
![image](https://github.com/user-attachments/assets/0859e65f-1062-4f00-9a42-d03e075e72e9)

What version of NSIS version are you using?

**Comment by 0-don** [comment]
https://v2.tauri.app/reference/config/#windowsconfig
https://v2.tauri.app/reference/config/#nsisconfig

the changes can only be done via `src-tauri/tauri.conf.json`

I am not very familiar with nsis process because its automated via github actions that are provided by tauri

**Comment by bovirus** [comment]
@0-don 
It seems that taury has a very "basic" function for integration with NSIS.
Didn't set PRODUCT VERSION (use for top left installation window)
Didn't set message for copyright in exe installer properties
Didn't setup Programn description in  in exe installer properties

What's NSIS version are you instaleld in your system?

**Comment by 0-don** [comment]
I hope copyright and description should be there after the build, I added few keys into `tauri.conf.json`.

I am on linux, I dont use windows currently

**Comment by bovirus** [comment]
@0-don 

Probably you are you using NSISI 2.x with very obsolete italian language file.
I attached the revsied Italian language file for version 2.5x.
Please replace the current Italian NSIS language file (I'm the NSIS Italian language).

[NSIS-2.51-ita-revised 2020.03.28.zip](https://github.com/user-attachments/files/18255328/NSIS-2.51-ita-revised.2020.03.28.zip)

**Comment by 0-don** [comment]
I didnt create the nsis config myself its done by the github action `.github/workflows/release.yml` which is provided by tauri

https://github.com/tauri-apps/tauri-action

**Comment by bovirus** [comment]
@0-don 

Please use my language file for NSIS.
When will be available next build I will check it.
Thanks.

**Comment by 0-don** [comment]
I dont know how to integrate them, I hope you can find it out and make a pull request

**Comment by bovirus** [comment]
@0-don 

Does in your system not installed NSIS?

**Comment by 0-don** [comment]
no
