### ISSUE TITLE
Bug report & some suggestions

### ISSUE THREAD

**Issue by edelvarden** [0-don/clippy#2]
Hi, not a bad implementation, but it needs some improvements to work safely with large data.

### 1. Interface Interaction Slows Down After Copying Several Large Images

Steps:
1. Copy some large images; for example, [one](https://static.scientificamerican.com/sciam/cache/file/E5DD54CA-0526-4E85-BFCB8AFBFA9E33C5_source.jpg), [two](https://media.cntraveller.com/photos/611bf0b8f6bd8f17556db5e4/master/pass/gettyimages-1146431497.jpg), [three](https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Shaqi_jrvej.jpg/1200px-Shaqi_jrvej.jpg).
2. Open the app main window.
3. Interact with the UI, e.g., switch between "Recent" and "Starred" tabs, type a search query, and scroll through the list.

### 2. Slow First Run If Several Large Images Are Copied

Steps:
1. Copy the same images and save them to the database file.
2. Open the app main window.

After these steps, the app freezes with high CPU usage. After several seconds, it shows the copied items, but interaction with UI is impossible.

### Suggestions to Fix This Problem

1. Set a limit by image size.
2. Save to the database only the pinned images.
3. Implement an option to limit non-pinned elements. For example, if the limit is 100 and a new element is being copied, remove the oldest element.

Maybe also using the following image conversion to WebP to optimize images before adding them to the list or saving them to the database.

```tsx
export const webpConversion = async (file: File): Promise<File> => {
  const bitmap = await createImageBitmap(file)
  const canvas = document.createElement("canvas")
  const context = canvas.getContext("2d")

  canvas.width = bitmap.width
  canvas.height = bitmap.height
  context?.drawImage(bitmap, 0, 0)

  return await new Promise<File>((resolve) => {
    canvas.toBlob(
      (blob) => {
        const [name] = file.name.split(".")
        const convertedFile = new File([blob as Blob], `${name}.webp`, {
          type: "image/webp",
        })
        resolve(convertedFile)
      },
      "image/webp",
      1
    )
  })
}
```

You can ignore this if it's difficult to implement, but these insights can help further enhance the performance and usability of our app.

**Comment by 0-don** [comment]
thanks for the report I look into it

**Comment by 0-don** [comment]
I hope I fixed your problem.

I resize the images to max 1280 pixels
and on clipboards fetch I convert the clipboards to base64 so I dont have to do any conversion in the frontend 
and updated all dependencies aswell

**Comment by edelvarden** [comment]
Yes, it helped, thanks for that
